sudo: required
dist: xenial
language: ruby
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y shellcheck
before_script:
  - export PATH="$HOME/.cabal/bin/:$PATH"
rvm:
- 2.0.0
- 2.1
- 2.2
- 2.3.1
- 2.4
- 2.5
